services:
    logger-basic-test:
        build: ${PROJECT_ROOT}/integ/logger
        logging:
            driver: fluentd
            options:
                tag: "basic-test-${TAG}"
                fluentd-address: tcp://${FLUENT_CONTAINER_IP}:24542
    logger-log-key:
        build: ${PROJECT_ROOT}/integ/logger
        logging:
            driver: fluentd
            options:
                tag: "log-key-test-${TAG}"
                fluentd-address: tcp://${FLUENT_CONTAINER_IP}:24542
    logger-emf:
        build: ${PROJECT_ROOT}/integ/emf_logger
        environment:
            - "EMF_METRIC_NAME_PATH=C:/out/expected-metric-name"
            - "FLUENT_CONTAINER_IP=${FLUENT_CONTAINER_IP}"
        logging:
            driver: fluentd
            options:
                tag: "log-emf-test-${TAG}"
                fluentd-address: tcp://${FLUENT_CONTAINER_IP}:24542
        # this volume is used for synchronization between the test
        # and the validator
        volumes:
            - ${PROJECT_ROOT}/integ/out:C:/out
networks:
    default:
        name: nat
        external: true